[package]
name = "xp-rust-01"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
tokio = { version = "1", features = ["full"] }
derive_more = {version="1.0.0-beta",features=["from"]}

[dev-dependencies]
anyhow = "1"